apiVersion: apps/v1
kind: Deployment
metadata:
  name: foaas
  labels:
    app: foaas
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foaas
  template:
    metadata:
      labels:
        app: foaas
    spec:
      containers:
      - name: foaas
        image: pincher95/foaas:2
        ports:
        - containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: foaas
spec:
  type: ClusterIP
  selector:
    app: foaas
  ports:
    - port: 80 # Default port for image
      targetPort: 5000