---
# tasks file for container
- name: Install Docker Module for Python
  pip:
   name: docker

- name: Pull default Docker image
  docker_image:
   name: "{{ default_container_image }}"
   source: pull

- name: Create default containers
  docker_container:
   name: "{{ default_container_name }}"
   image: "{{ default_container_image }}"
   #command: "{{ default_container_command }}"
   state: present
