---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-master
  namespace: default
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "app.kubernetes.io/instance": "jenkins-master"
    "app.kubernetes.io/component": "jenkins-master"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jenkins-master-schedule-agents
  namespace: default
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "app.kubernetes.io/instance": "jenkins-master"
    "app.kubernetes.io/component": "jenkins-master"
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec", "persistentvolumeclaims"]
    verbs: ["create", "delete", "get", "list","patch", "update", "watch", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-master-schedule-agents
  namespace: default
  labels:
    "app.kubernetes.io/name": 'jenkins'
    "app.kubernetes.io/instance": "jenkins-master"
    "app.kubernetes.io/component": "jenkins-master"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-master-schedule-agents
subjects:
  - kind: ServiceAccount
    name: jenkins-master
    namespace: default