---
#---------------Debian install----------------
- name: Remove old Docker and Docker-engine packages
  apt:
   name:
   - docker
   - docker-engine
   - docker.io
   - containerd
   - runc
   state: absent


- name: Install required system packages APT management systems
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: latest
    update_cache: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    update_cache: yes
    state: present

- name: Update apt and install docker-ce
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    update_cache: yes
    state: present

- name: Add user to Docker group
  user:
    name: "{{ item }}"
    group: docker
    append: yes
  with_items: "{{ docker_users }}"