# name your datacenter
global:
  datacenter: dc1

server:
  # use 1 server
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  hostNetwork: false

client:
  enabled: true
  # enable grpc on your client to support consul consul connect
  grpc: true
  exposeGossipPorts: true

syncCatalog:
  enabled: true
  toConsul: true
  toK8S: true

dns:
  enabled: true
#  clusterIP: 172.20.4.180

ui:
  enabled: true
  service:
    type: 'NodePort'
    nodePort: 30085

connectInject:
  enabled: true
  # inject an envoy sidecar into every new pod, except for those with annotations that prevent injection
  default: true
  # these settings enable L7 metrics collection and are new in 1.5
  centralConfig:
    enabled: true
    # set the default protocol (cab be overwritten with annotations)
    defaultProtocol: "http"
    # tell envoy where  to send metrics
    proxyDefaults: |
      {
      "envoy_dogstatsd_url": "udp://127.0.0.1:9125"
      }
