config:
  filebeat.config:
    modules:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

  processors:
    - add_cloud_metadata:

  filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/*.log
        - /var/log/messages
        - /var/log/syslog
        - /var/log/containers/*.log
    - type: docker
      containers.ids:
        - "*"
      processors:
        - add_kubernetes_metadata:
        - drop_event:
            when:
              equals:
                kubernetes.container.name: "filebeat"

  output.file.enabled: false
  output.logstash:
    hosts: ["logstash-kube-logging.service.consul:5044"]

monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
#    namespace: kube-metrics
#    interval: 30s
#    telemetryPath: /metrics
#    labels:
#      - consul.hashicorp.com/service-tags: filebeat-metrics

