controller:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3

  service:
    enabled: true
    annotations: {
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    }
    externalTrafficPolicy: Local

  metrics:
    enabled: true
    service:
      annotations: {
        consul.hashicorp.com/service-tags: nginx-metrics,
        enable-vts-status: "true",
        prometheus.io/scrape: "true",
        prometheus.io/port: "10254"
      }
